### ISSUE TITLE
Can't rerun snio import

### ISSUE THREAD

**Issue by hashtagnulla** [SenseNet/sn-io#59]
When I try to rerun a content import, I get a strange error message and the import process stops immediately.

Strack trace:
``` text
2024-03-12 01:25:29.983 +01:00 [VRB] Updated  /Root/Content/SNBooking/2023
2024-03-12 01:25:30.884 +01:00 [VRB] Updated  /Root/Content/SNBooking/2023/Employees
2024-03-12 01:25:30.888 +01:00 [ERR] After parsing a value an unexpected character was encountered: ". Path 'Fields.User', line 12, position 4.
Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: ". Path 'Fields.User', line 12, position 4.
   at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader, Boolean writeChildren, Boolean writeDateConstructorAsDate, Boolean writeComments)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJObject(JsonReader reader)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at SenseNet.IO.Implementations.FsContent.InitializeMetadata(String[] fieldNames, Nullable`1 withoutPermissions) in C:\Users\nagyv\Repositories\sn-io\src\SenseNet.IO\Implementations\FsContent.cs:line 149
   at SenseNet.IO.Implementations.FsReader.ReadChildren(FsContent parentContent) in C:\Users\nagyv\Repositories\sn-io\src\SenseNet.IO\Implementations\FsReader.cs:line 278
   at SenseNet.IO.Implementations.FsReader.MoveToFirstChild(TreeState state) in C:\Users\nagyv\Repositories\sn-io\src\SenseNet.IO\Implementations\FsReader.cs:line 242
   at SenseNet.IO.Implementations.FsReader.ReadTree(TreeState state) in C:\Users\nagyv\Repositories\sn-io\src\SenseNet.IO\Implementations\FsReader.cs:line 180
   at SenseNet.IO.Implementations.FsReader.ReadAllAsync(String[] contentsWithoutChildren, CancellationToken cancel) in C:\Users\nagyv\Repositories\sn-io\src\SenseNet.IO\Implementations\FsReader.cs:line 119
   at SenseNet.IO.Implementations.SemanticContentFlow.CopyAllAsync(String[] skippedSubTreePaths, IProgress`1 progress, CancellationToken cancel) in C:\Users\nagyv\Repositories\sn-io\src\SenseNet.IO\Implementations\SemanticContentFlow.cs:line 169
   at SenseNet.IO.Implementations.SemanticContentFlow.TransferAsync(IProgress`1 progress, CancellationToken cancel) in C:\Users\nagyv\Repositories\sn-io\src\SenseNet.IO\Implementations\SemanticContentFlow.cs:line 75
   at SenseNet.IO.CLI.IoApp.RunAsync(Action`1 progressCallback) in C:\Users\nagyv\Repositories\sn-io\src\SenseNet.IO.CLI\IoApp.cs:line 42
```

**Comment by hashtagnulla** [comment]
Tried to reproduce it today, but I couldn't. Must have been some manual modification there that I didn't see.
